title: Joeseph Luciano

#logo: /assets/img/headshot_circle.png
#the profile image

#description: text below the image
#below the icon in template

#show_downloads: false
#download code or not

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
